### ISSUE TITLE
lux_0.24.0_Linux_arm64 can not run

### ISSUE THREAD

**Issue by mzhboy** [iawia002/lux#1340]
lux_0.24.0_Linux_arm64 can't run.
0.23.0 works

>   ># file lux
> lux: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=gV_PsgOoRpL2mjKxWZkd/qOClEr0V4B7CCz5BQ0fT/MsmnJdSRlyCprsgIn-bd/QxfxfylUYMMFUg-IZEwZ, stripped

**Comment by iawia002** [comment]
I don't have a Linux arm64 machine, what's the output of `lux -v`?

**Comment by mzhboy** [comment]
> I don't have a Linux arm64 machine, what's the output of `lux -v`?

木有输出，挂那里了，没有下一步

**Comment by mzhboy** [comment]
> root@rpi4b2:/tmp/24# lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 22.04.4 LTS
> Release:	22.04
> Codename:	jammy
>

**Comment by mzhboy** [comment]
> root@rpi4b2:/tmp/24# dlv exec ./lux
> 2024-04-22T07:04:38Z error layer=debugger can't find build-id note on binary
> panic: runtime error: slice bounds out of range [:2] with length 0
> 
> goroutine 1 [running]:
> github.com/go-delve/delve/pkg/proc.(*BinaryInfo).openSeparateDebugInfo(0x40002388c0, 0x40001981c0, 0x40001190e0, {0x400020cc80, 0x1, 0x1})
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:1213 +0x7bc
> github.com/go-delve/delve/pkg/proc.loadBinaryInfoElf(0x40002388c0, 0x40001981c0, {0xffffe4d7e781, 0x5}, 0x7c260, 0x4000022f10)
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:1297 +0x23c
> github.com/go-delve/delve/pkg/proc.loadBinaryInfo(0x40002388c0, 0x40001981c0, {0xffffe4d7e781, 0x5}, 0x7c260)
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:671 +0x178
> github.com/go-delve/delve/pkg/proc.(*BinaryInfo).AddImage(0x40002388c0, {0xffffe4d7e781, 0x5}, 0x7c260)
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:831 +0x364
> github.com/go-delve/delve/pkg/proc.(*BinaryInfo).LoadBinaryInfo(0x40002388c0, {0xffffe4d7e781, 0x5}, 0x7c260, {0x400020cc80, 0x1, 0x1})
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:662 +0xfc
> github.com/go-delve/delve/pkg/proc.NewTarget({0xac0360, 0x4000330120}, 0xac2c6, {0xabd068, 0x400011f7a0}, {{0xffffe4d7e781, 0x5}, {0x400020cc80, 0x1, 0x1}, ...})
> 	github.com/go-delve/delve/pkg/proc/target.go:183 +0x98
> github.com/go-delve/delve/pkg/proc/native.(*nativeProcess).initialize(0x4000330120, {0xffffe4d7e781, 0x5}, {0x400020cc80, 0x1, 0x1})
> 	github.com/go-delve/delve/pkg/proc/native/proc.go:268 +0x104
> github.com/go-delve/delve/pkg/proc/native.Launch({0x400020ce80, 0x1, 0x1}, {0x9ddb7d, 0x1}, 0x0, {0x400020cc80, 0x1, 0x1}, {0x0, ...}, ...)
> 	github.com/go-delve/delve/pkg/proc/native/proc_linux.go:134 +0x47c
> github.com/go-delve/delve/service/debugger.(*Debugger).Launch(0x400023e0b0, {0x400020ce80, 0x1, 0x1}, {0x9ddb7d, 0x1})
> 	github.com/go-delve/delve/service/debugger/debugger.go:305 +0x484
> github.com/go-delve/delve/service/debugger.New(0x4000354000, {0x400020ce80, 0x1, 0x1})
> 	github.com/go-delve/delve/service/debugger/debugger.go:190 +0x4cc
> github.com/go-delve/delve/service/rpccommon.(*ServerImpl).Run(0x4000208840)
> 	github.com/go-delve/delve/service/rpccommon/server.go:122 +0xec
> github.com/go-delve/delve/cmd/dlv/cmds.execute(0x0, {0x400020ce80, 0x1, 0x1}, 0x400021add0, {0x0, 0x0}, 0x0, {0x400020ce80, 0x1, ...}, ...)
> 	github.com/go-delve/delve/cmd/dlv/cmds/commands.go:971 +0xcf0
> github.com/go-delve/delve/cmd/dlv/cmds.New.func4(0x400023bb80, {0x400020ce80, 0x1, 0x1})
> 	github.com/go-delve/delve/cmd/dlv/cmds/commands.go:252 +0x80
> github.com/spf13/cobra.(*Command).execute(0x400023bb80, {0x400020ce50, 0x1, 0x1})
> 	github.com/spf13/cobra/command.go:860 +0x650
> github.com/spf13/cobra.(*Command).ExecuteC(0x400023af00)
> 	github.com/spf13/cobra/command.go:974 +0x424
> github.com/spf13/cobra.(*Command).Execute(...)
> 	github.com/spf13/cobra/command.go:902
> main.main()
> 	github.com/go-delve/delve/cmd/dlv/main.go:24 +0x1e0
>

**Comment by mzhboy** [comment]
好奇怪，在一台 rpi4 上使用 
`dlv exec ./lux -- -v`
命令测试 0.23 版本后，同命令测试 0.24 版本也可以运行了。

----------------------

于是重启系统再次测试，发现 `dlv exec ./lux -- -v` 命令，在 0.23 下可以立即得到结果； 0.24 下需要等待几分钟得到结果。之后 `./lux -v` 可以立即得到结果。下面贴有价值的 0.24 的日志。

> 
> root@rpi4b2:/tmp/24# tar xf lux_0.24.0_Linux_arm64.tar.gz 
> root@rpi4b2:/tmp/24# ./lux -v
> ^C
> root@rpi4b2:/tmp/24# dlv exec ./lux -- -v
> 2024-04-22T07:16:14Z error layer=debugger can't find build-id note on binary
> panic: runtime error: slice bounds out of range [:2] with length 0
> 
> goroutine 1 [running]:
> github.com/go-delve/delve/pkg/proc.(*BinaryInfo).openSeparateDebugInfo(0x40001408c0, 0x400007c000, 0x400007e000, {0x4000114c60, 0x1, 0x1})
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:1213 +0x7bc
> github.com/go-delve/delve/pkg/proc.loadBinaryInfoElf(0x40001408c0, 0x400007c000, {0xfffff6f7077f, 0x5}, 0x7c260, 0x40000222d0)
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:1297 +0x23c
> github.com/go-delve/delve/pkg/proc.loadBinaryInfo(0x40001408c0, 0x400007c000, {0xfffff6f7077f, 0x5}, 0x7c260)
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:671 +0x178
> github.com/go-delve/delve/pkg/proc.(*BinaryInfo).AddImage(0x40001408c0, {0xfffff6f7077f, 0x5}, 0x7c260)
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:831 +0x364
> github.com/go-delve/delve/pkg/proc.(*BinaryInfo).LoadBinaryInfo(0x40001408c0, {0xfffff6f7077f, 0x5}, 0x7c260, {0x4000114c60, 0x1, 0x1})
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:662 +0xfc
> github.com/go-delve/delve/pkg/proc.NewTarget({0xac0360, 0x4000232120}, 0x4df, {0xabd068, 0x4000074000}, {{0xfffff6f7077f, 0x5}, {0x4000114c60, 0x1, 0x1}, ...})
> 	github.com/go-delve/delve/pkg/proc/target.go:183 +0x98
> github.com/go-delve/delve/pkg/proc/native.(*nativeProcess).initialize(0x4000232120, {0xfffff6f7077f, 0x5}, {0x4000114c60, 0x1, 0x1})
> 	github.com/go-delve/delve/pkg/proc/native/proc.go:268 +0x104
> github.com/go-delve/delve/pkg/proc/native.Launch({0x4000250090, 0x2, 0x3}, {0x9ddb7d, 0x1}, 0x0, {0x4000114c60, 0x1, 0x1}, {0x0, ...}, ...)
> 	github.com/go-delve/delve/pkg/proc/native/proc_linux.go:134 +0x47c
> github.com/go-delve/delve/service/debugger.(*Debugger).Launch(0x40001460b0, {0x4000250090, 0x2, 0x3}, {0x9ddb7d, 0x1})
> 	github.com/go-delve/delve/service/debugger/debugger.go:305 +0x484
> github.com/go-delve/delve/service/debugger.New(0x4000254000, {0x4000250090, 0x2, 0x3})
> 	github.com/go-delve/delve/service/debugger/debugger.go:190 +0x4cc
> github.com/go-delve/delve/service/rpccommon.(*ServerImpl).Run(0x40001107e0)
> 	github.com/go-delve/delve/service/rpccommon/server.go:122 +0xec
> github.com/go-delve/delve/cmd/dlv/cmds.execute(0x0, {0x4000250090, 0x2, 0x3}, 0x4000126c30, {0x0, 0x0}, 0x0, {0x4000250090, 0x2, ...}, ...)
> 	github.com/go-delve/delve/cmd/dlv/cmds/commands.go:971 +0xcf0
> github.com/go-delve/delve/cmd/dlv/cmds.New.func4(0x4000143b80, {0x4000250090, 0x2, 0x3})
> 	github.com/go-delve/delve/cmd/dlv/cmds/commands.go:252 +0x80
> github.com/spf13/cobra.(*Command).execute(0x4000143b80, {0x4000250060, 0x3, 0x3})
> 	github.com/spf13/cobra/command.go:860 +0x650
> github.com/spf13/cobra.(*Command).ExecuteC(0x4000142f00)
> 	github.com/spf13/cobra/command.go:974 +0x424
> github.com/spf13/cobra.(*Command).Execute(...)
> 	github.com/spf13/cobra/command.go:902
> main.main()
> 	github.com/go-delve/delve/cmd/dlv/main.go:24 +0x1e0
> root@rpi4b2:/tmp/24# dlv exec ./lux -- -v
> 2024-04-22T07:16:37Z error layer=debugger can't find build-id note on binary
> panic: runtime error: slice bounds out of range [:2] with length 0
> 
> goroutine 1 [running]:
> github.com/go-delve/delve/pkg/proc.(*BinaryInfo).openSeparateDebugInfo(0x400012adc0, 0x4000236000, 0x4000238000, {0x40001accf0, 0x1, 0x1})
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:1213 +0x7bc
> github.com/go-delve/delve/pkg/proc.loadBinaryInfoElf(0x400012adc0, 0x4000236000, {0xfffff066d77f, 0x5}, 0x7c260, 0x4000210200)
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:1297 +0x23c
> github.com/go-delve/delve/pkg/proc.loadBinaryInfo(0x400012adc0, 0x4000236000, {0xfffff066d77f, 0x5}, 0x7c260)
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:671 +0x178
> github.com/go-delve/delve/pkg/proc.(*BinaryInfo).AddImage(0x400012adc0, {0xfffff066d77f, 0x5}, 0x7c260)
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:831 +0x364
> github.com/go-delve/delve/pkg/proc.(*BinaryInfo).LoadBinaryInfo(0x400012adc0, {0xfffff066d77f, 0x5}, 0x7c260, {0x40001accf0, 0x1, 0x1})
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:662 +0xfc
> github.com/go-delve/delve/pkg/proc.NewTarget({0xac0360, 0x4000188510}, 0x59d, {0xabd068, 0x400022e000}, {{0xfffff066d77f, 0x5}, {0x40001accf0, 0x1, 0x1}, ...})
> 	github.com/go-delve/delve/pkg/proc/target.go:183 +0x98
> github.com/go-delve/delve/pkg/proc/native.(*nativeProcess).initialize(0x4000188510, {0xfffff066d77f, 0x5}, {0x40001accf0, 0x1, 0x1})
> 	github.com/go-delve/delve/pkg/proc/native/proc.go:268 +0x104
> github.com/go-delve/delve/pkg/proc/native.Launch({0x40002967b0, 0x2, 0x3}, {0x9ddb7d, 0x1}, 0x0, {0x40001accf0, 0x1, 0x1}, {0x0, ...}, ...)
> 	github.com/go-delve/delve/pkg/proc/native/proc_linux.go:134 +0x47c
> github.com/go-delve/delve/service/debugger.(*Debugger).Launch(0x400014cfd0, {0x40002967b0, 0x2, 0x3}, {0x9ddb7d, 0x1})
> 	github.com/go-delve/delve/service/debugger/debugger.go:305 +0x484
> github.com/go-delve/delve/service/debugger.New(0x400019e1c0, {0x40002967b0, 0x2, 0x3})
> 	github.com/go-delve/delve/service/debugger/debugger.go:190 +0x4cc
> github.com/go-delve/delve/service/rpccommon.(*ServerImpl).Run(0x400007ed20)
> 	github.com/go-delve/delve/service/rpccommon/server.go:122 +0xec
> github.com/go-delve/delve/cmd/dlv/cmds.execute(0x0, {0x40002967b0, 0x2, 0x3}, 0x40001c6680, {0x0, 0x0}, 0x0, {0x40002967b0, 0x2, ...}, ...)
> 	github.com/go-delve/delve/cmd/dlv/cmds/commands.go:971 +0xcf0
> github.com/go-delve/delve/cmd/dlv/cmds.New.func4(0x40001cf180, {0x40002967b0, 0x2, 0x3})
> 	github.com/go-delve/delve/cmd/dlv/cmds/commands.go:252 +0x80
> github.com/spf13/cobra.(*Command).execute(0x40001cf180, {0x4000296780, 0x3, 0x3})
> 	github.com/spf13/cobra/command.go:860 +0x650
> github.com/spf13/cobra.(*Command).ExecuteC(0x40001ce500)
> 	github.com/spf13/cobra/command.go:974 +0x424
> github.com/spf13/cobra.(*Command).Execute(...)
> 	github.com/spf13/cobra/command.go:902
> main.main()
> 	github.com/go-delve/delve/cmd/dlv/main.go:24 +0x1e0
> root@rpi4b2:/tmp/24# ./lux -v
> ^C
> root@rpi4b2:/tmp/24# dlv exec ./lux -- -v
> 2024-04-22T07:17:04Z error layer=debugger can't find build-id note on binary
> panic: runtime error: slice bounds out of range [:2] with length 0
> 
> goroutine 1 [running]:
> github.com/go-delve/delve/pkg/proc.(*BinaryInfo).openSeparateDebugInfo(0x40000cedc0, 0x40001c0000, 0x40001c2000, {0x4000158cb0, 0x1, 0x1})
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:1213 +0x7bc
> github.com/go-delve/delve/pkg/proc.loadBinaryInfoElf(0x40000cedc0, 0x40001c0000, {0xfffffa5c177f, 0x5}, 0x7c260, 0x4000198210)
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:1297 +0x23c
> github.com/go-delve/delve/pkg/proc.loadBinaryInfo(0x40000cedc0, 0x40001c0000, {0xfffffa5c177f, 0x5}, 0x7c260)
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:671 +0x178
> github.com/go-delve/delve/pkg/proc.(*BinaryInfo).AddImage(0x40000cedc0, {0xfffffa5c177f, 0x5}, 0x7c260)
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:831 +0x364
> github.com/go-delve/delve/pkg/proc.(*BinaryInfo).LoadBinaryInfo(0x40000cedc0, {0xfffffa5c177f, 0x5}, 0x7c260, {0x4000158cb0, 0x1, 0x1})
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:662 +0xfc
> github.com/go-delve/delve/pkg/proc.NewTarget({0xac0360, 0x40001345a0}, 0x5bf, {0xabd068, 0x40001b8000}, {{0xfffffa5c177f, 0x5}, {0x4000158cb0, 0x1, 0x1}, ...})
> 	github.com/go-delve/delve/pkg/proc/target.go:183 +0x98
> github.com/go-delve/delve/pkg/proc/native.(*nativeProcess).initialize(0x40001345a0, {0xfffffa5c177f, 0x5}, {0x4000158cb0, 0x1, 0x1})
> 	github.com/go-delve/delve/pkg/proc/native/proc.go:268 +0x104
> github.com/go-delve/delve/pkg/proc/native.Launch({0x400024e660, 0x2, 0x3}, {0x9ddb7d, 0x1}, 0x0, {0x4000158cb0, 0x1, 0x1}, {0x0, ...}, ...)
> 	github.com/go-delve/delve/pkg/proc/native/proc_linux.go:134 +0x47c
> github.com/go-delve/delve/service/debugger.(*Debugger).Launch(0x40000f2c60, {0x400024e660, 0x2, 0x3}, {0x9ddb7d, 0x1})
> 	github.com/go-delve/delve/service/debugger/debugger.go:305 +0x484
> github.com/go-delve/delve/service/debugger.New(0x400014c1c0, {0x400024e660, 0x2, 0x3})
> 	github.com/go-delve/delve/service/debugger/debugger.go:190 +0x4cc
> github.com/go-delve/delve/service/rpccommon.(*ServerImpl).Run(0x4000092ea0)
> 	github.com/go-delve/delve/service/rpccommon/server.go:122 +0xec
> github.com/go-delve/delve/cmd/dlv/cmds.execute(0x0, {0x400024e660, 0x2, 0x3}, 0x4000170270, {0x0, 0x0}, 0x0, {0x400024e660, 0x2, ...}, ...)
> 	github.com/go-delve/delve/cmd/dlv/cmds/commands.go:971 +0xcf0
> github.com/go-delve/delve/cmd/dlv/cmds.New.func4(0x4000231180, {0x400024e660, 0x2, 0x3})
> 	github.com/go-delve/delve/cmd/dlv/cmds/commands.go:252 +0x80
> github.com/spf13/cobra.(*Command).execute(0x4000231180, {0x400024e630, 0x3, 0x3})
> 	github.com/spf13/cobra/command.go:860 +0x650
> github.com/spf13/cobra.(*Command).ExecuteC(0x4000230500)
> 	github.com/spf13/cobra/command.go:974 +0x424
> github.com/spf13/cobra.(*Command).Execute(...)
> 	github.com/spf13/cobra/command.go:902
> main.main()
> 	github.com/go-delve/delve/cmd/dlv/main.go:24 +0x1e0
> root@rpi4b2:/tmp/24# dlv exec ./lux -- -v
> 2024-04-22T07:18:05Z error layer=debugger can't find build-id note on binary
> panic: runtime error: slice bounds out of range [:2] with length 0
> 
> goroutine 1 [running]:
> github.com/go-delve/delve/pkg/proc.(*BinaryInfo).openSeparateDebugInfo(0x40002b48c0, 0x40001a01c0, 0x40001210e0, {0x4000286c80, 0x1, 0x1})
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:1213 +0x7bc
> github.com/go-delve/delve/pkg/proc.loadBinaryInfoElf(0x40002b48c0, 0x40001a01c0, {0xffffe5aaa77f, 0x5}, 0x7c260, 0x4000022f60)
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:1297 +0x23c
> github.com/go-delve/delve/pkg/proc.loadBinaryInfo(0x40002b48c0, 0x40001a01c0, {0xffffe5aaa77f, 0x5}, 0x7c260)
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:671 +0x178
> github.com/go-delve/delve/pkg/proc.(*BinaryInfo).AddImage(0x40002b48c0, {0xffffe5aaa77f, 0x5}, 0x7c260)
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:831 +0x364
> github.com/go-delve/delve/pkg/proc.(*BinaryInfo).LoadBinaryInfo(0x40002b48c0, {0xffffe5aaa77f, 0x5}, 0x7c260, {0x4000286c80, 0x1, 0x1})
> 	github.com/go-delve/delve/pkg/proc/bininfo.go:662 +0xfc
> github.com/go-delve/delve/pkg/proc.NewTarget({0xac0360, 0x40003161b0}, 0x5ce, {0xabd068, 0x40001277a0}, {{0xffffe5aaa77f, 0x5}, {0x4000286c80, 0x1, 0x1}, ...})
> 	github.com/go-delve/delve/pkg/proc/target.go:183 +0x98
> github.com/go-delve/delve/pkg/proc/native.(*nativeProcess).initialize(0x40003161b0, {0xffffe5aaa77f, 0x5}, {0x4000286c80, 0x1, 0x1})
> 	github.com/go-delve/delve/pkg/proc/native/proc.go:268 +0x104
> github.com/go-delve/delve/pkg/proc/native.Launch({0x40003480f0, 0x2, 0x3}, {0x9ddb7d, 0x1}, 0x0, {0x4000286c80, 0x1, 0x1}, {0x0, ...}, ...)
> 	github.com/go-delve/delve/pkg/proc/native/proc_linux.go:134 +0x47c
> github.com/go-delve/delve/service/debugger.(*Debugger).Launch(0x40002ba0b0, {0x40003480f0, 0x2, 0x3}, {0x9ddb7d, 0x1})
> 	github.com/go-delve/delve/service/debugger/debugger.go:305 +0x484
> github.com/go-delve/delve/service/debugger.New(0x400034c000, {0x40003480f0, 0x2, 0x3})
> 	github.com/go-delve/delve/service/debugger/debugger.go:190 +0x4cc
> github.com/go-delve/delve/service/rpccommon.(*ServerImpl).Run(0x4000280780)
> 	github.com/go-delve/delve/service/rpccommon/server.go:122 +0xec
> github.com/go-delve/delve/cmd/dlv/cmds.execute(0x0, {0x40003480f0, 0x2, 0x3}, 0x4000296b60, {0x0, 0x0}, 0x0, {0x40003480f0, 0x2, ...}, ...)
> 	github.com/go-delve/delve/cmd/dlv/cmds/commands.go:971 +0xcf0
> github.com/go-delve/delve/cmd/dlv/cmds.New.func4(0x40002b7b80, {0x40003480f0, 0x2, 0x3})
> 	github.com/go-delve/delve/cmd/dlv/cmds/commands.go:252 +0x80
> github.com/spf13/cobra.(*Command).execute(0x40002b7b80, {0x40003480c0, 0x3, 0x3})
> 	github.com/spf13/cobra/command.go:860 +0x650
> github.com/spf13/cobra.(*Command).ExecuteC(0x40002b6f00)
> 	github.com/spf13/cobra/command.go:974 +0x424
> github.com/spf13/cobra.(*Command).Execute(...)
> 	github.com/spf13/cobra/command.go:902
> main.main()
> 	github.com/go-delve/delve/cmd/dlv/main.go:24 +0x1e0
> root@rpi4b2:/tmp/24# 
> lux: version 0.24.0, A fast and simple video downloader.
> 
> 
> lux: version 0.24.0, A fast and simple video downloader.
> 
> 
> lux: version 0.24.0, A fast and simple video downloader.
> 
> 
> root@rpi4b2:/tmp/24# ./lux -v
> 
> lux: version 0.24.0, A fast and simple video downloader.
> 
> root@rpi4b2:/tmp/24# 
> lux: version 0.24.0, A fast and simple video downloader.
>

**Comment by mzhboy** [comment]
> root@rpi4b1:/tmp/24# time ./lux -v
> 
> lux: version 0.24.0, A fast and simple video downloader.
> 
> 
> real	2m24.369s
> user	0m3.819s
> sys	0m0.760s
>

**Comment by truboxl** [comment]
Absolute worst case after repeating running lux
```console
$ strace -c ./lux
Run lux failed: too few arguments
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- -------------------
 95.78    1.099493          74     14813     10519 rt_sigreturn
  1.10    0.012603         157        80         7 futex
  0.48    0.005493          23       229           mmap
  0.25    0.002862          21       133           mprotect
  0.22    0.002509         418         6         4 epoll_ctl
  0.20    0.002250          33        67         9 openat
  0.19    0.002222          21       104           prctl
  0.18    0.002117          23        91           munmap
  0.18    0.002042          68        30           rt_sigprocmask
  0.18    0.002026          33        60           read
  0.15    0.001699          65        26           fcntl
  0.12    0.001390          21        65         5 newfstatat
  0.11    0.001265          31        40           readlinkat
  0.11    0.001224        1224         1           timer_delete
  0.10    0.001174          21        55           close
  0.10    0.001133          20        55           fstat
  0.09    0.001063         265         4           clone
  0.08    0.000930           7       124           rt_sigaction
  0.08    0.000903         150         6           sched_yield
  0.06    0.000701          25        28        23 faccessat
  0.06    0.000659         659         1           execve
  0.05    0.000520          30        17           pread64
  0.03    0.000371          23        16           mremap
  0.02    0.000252         126         2           epoll_pwait
  0.02    0.000192          21         9           fstatfs
  0.01    0.000133         133         1           ioctl
  0.01    0.000123         123         1           setitimer
  0.01    0.000112         112         1           prlimit64
  0.01    0.000088          88         1           nanosleep
  0.01    0.000061          20         3         2 madvise
  0.00    0.000051          51         1           pipe2
  0.00    0.000047          47         1           epoll_create1
  0.00    0.000045          22         2           getrandom
  0.00    0.000039          39         1           timer_settime
  0.00    0.000038          38         1           timer_create
  0.00    0.000026          26         1           getpid
  0.00    0.000023          23         1           set_tid_address
  0.00    0.000020          20         1           sched_getscheduler
  0.00    0.000020          20         1           sched_getaffinity
  0.00    0.000019           9         2           sigaltstack
  0.00    0.000019          19         1           getuid
  0.00    0.000000           0         1           gettid
------ ----------- ----------- --------- --------- -------------------
100.00    1.147957          71     16083     10569 total
```
Note the high amount of rt_sigreturn

Others strace logs also pointing to a lot of SIGURG. But I can't point where is it coming from. https://github.com/iawia002/lux/compare/v0.23.0...v0.24.0

**Comment by Zcodeoooo** [comment]
x64 0.24,也有偶尔该死锁的情况

**Comment by Zcodeoooo** [comment]
Linux_X64 0.24, there are also occasional deadlocks. From the trace, it is likely caused by file descriptor related operations, and we are preparing to debug with gdb

**Comment by mzhboy** [comment]
test after reboot 

```
root@rpi4b2:/tmp/24# strace -c ./lux -v

lux: version 0.24.0, A fast and simple video downloader.

% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ------------------
 84.55    3.735430          83     44718           rt_sigreturn
 15.19    0.671139         697       962        75 futex
  0.09    0.003980          34       114           rt_sigaction
  0.06    0.002470          39        62           write
  0.03    0.001150          52        22           mmap
  0.02    0.000837         139         6           sched_yield
  0.01    0.000644         214         3           clone
  0.01    0.000375          28        13           fcntl
  0.01    0.000354          44         8           rt_sigprocmask
  0.01    0.000338          42         8           pread64
  0.00    0.000186         186         1           readlinkat
  0.00    0.000179          44         4         2 epoll_ctl
  0.00    0.000160          40         4           openat
  0.00    0.000113          56         2         1 newfstatat
  0.00    0.000107          53         2           madvise
  0.00    0.000094          94         1           pipe2
  0.00    0.000083          41         2           prlimit64
  0.00    0.000068          68         1           epoll_create1
  0.00    0.000066          33         2           sigaltstack
  0.00    0.000047          47         1           ioctl
  0.00    0.000047          15         3           close
  0.00    0.000043          43         1           fstat
  0.00    0.000030          30         1           gettid
  0.00    0.000000           0         2           epoll_pwait
  0.00    0.000000           0         1           read
  0.00    0.000000           0         1           sched_getaffinity
  0.00    0.000000           0         1           execve
------ ----------- ----------- --------- --------- ------------------
100.00    4.417940          96     45946        78 total
root@rpi4b2:/tmp/24# strace -c ./lux -v

lux: version 0.24.0, A fast and simple video downloader.

% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ------------------
 16.29    0.001315        1315         1           execve
 13.96    0.001127          53        21           rt_sigreturn
 12.66    0.001022           8       114           rt_sigaction
  9.91    0.000800          36        22           mmap
  6.49    0.000524         174         3           clone
  5.92    0.000478          59         8           rt_sigprocmask
  5.15    0.000416          32        13           fcntl
  4.71    0.000380          47         8           futex
  4.04    0.000326          40         8           pread64
  3.99    0.000322          80         4           openat
  3.87    0.000312         156         2           sched_yield
  2.32    0.000187         187         1           readlinkat
  2.23    0.000180          45         4         2 epoll_ctl
  1.41    0.000114          38         3           close
  1.31    0.000106         106         1           pipe2
  1.00    0.000081          40         2           prlimit64
  0.83    0.000067          22         3           read
  0.76    0.000061          61         1           epoll_create1
  0.67    0.000054          27         2           madvise
  0.56    0.000045          22         2           sigaltstack
  0.53    0.000043          21         2           fstat
  0.47    0.000038          38         1           sched_getaffinity
  0.33    0.000027          27         1           ioctl
  0.33    0.000027          13         2           newfstatat
  0.25    0.000020          20         1           gettid
  0.00    0.000000           0         1           write
------ ----------- ----------- --------- --------- ------------------
100.00    0.008072          34       231         2 total
```

**Comment by iawia002** [comment]
Please try with [v0.24.1](https://github.com/iawia002/lux/releases/tag/v0.24.1), I have bumped the go version to 1.22, hope this is a cross-compile issue

**Comment by arthurqiao** [comment]
> Please try with [v0.24.1](https://github.com/iawia002/lux/releases/tag/v0.24.1), I have bumped the go version to 1.22, hope this is a cross-compile issue

I updated the v0.24.1 version, and it still takes 2-3 minutes to start for the first time, and the version number is still incorrect, it shows v0.0.0.

<img width="697" alt="截屏2024-05-06 15 03 46" src="https://github.com/iawia002/lux/assets/167514194/9c226225-06b7-42c7-843e-58217b0f59f5">

**Comment by iawia002** [comment]
Which binary did you download? From https://github.com/iawia002/lux/releases/tag/v0.24.1 here?

**Comment by arthurqiao** [comment]
> Which binary did you download? From https://github.com/iawia002/lux/releases/tag/v0.24.1 here?
> 
> NOTE: The version number will only be displayed in the binary file from the [release page](https://github.com/iawia002/lux/releases)

The early version was installed via Homebrew and updated to v0.24.1 today in the terminal with "brew upgrade lux".

**Comment by arthurqiao** [comment]
> > Which binary did you download? From https://github.com/iawia002/lux/releases/tag/v0.24.1 here?
> > NOTE: The version number will only be displayed in the binary file from the [release page](https://github.com/iawia002/lux/releases)
> 
> The early version was installed via Homebrew and updated to v0.24.1 today in the terminal with "brew upgrade lux".

Through the following operations, lux can start quickly, but the version number is still incorrect.
1. brew uninstall lux
2. restart MacBook
3. brew install lux
<img width="697" alt="截屏2024-05-06 20 42 46" src="https://github.com/iawia002/lux/assets/167514194/a131463b-e483-488d-90b1-8cfa9c4d8ce5">

**Comment by HXHGTS** [comment]
升级0.24.1以后，还是同样的问题😂

**Comment by tqfx** [comment]
```
$ strace -c lux -v

lux: version v0.0.0, A fast and simple video downloader.

% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- -------------------
 98.88    2.697803          16    165303           rt_sigreturn
  0.20    0.005570          28       198           mmap
  0.15    0.004005          32       124           rt_sigaction
  0.10    0.002689          76        35         2 futex
  0.09    0.002514          20       121           mprotect
  0.09    0.002369          29        79           munmap
  0.07    0.001995          32        62         5 openat
  0.06    0.001660          25        66         5 newfstatat
  0.05    0.001485          14       106           prctl
  0.05    0.001366          35        38           readlinkat
  0.05    0.001271          22        56           close
  0.05    0.001238          22        54           fstat
  0.04    0.001192          49        24           rt_sigprocmask
  0.02    0.000655          34        19           fcntl
  0.02    0.000526           8        62           read
  0.01    0.000398          39        10           mremap
  0.01    0.000376          26        14           pread64
  0.01    0.000297          99         3           clone
  0.01    0.000174          29         6           fstatfs
  0.00    0.000109          27         4         2 epoll_ctl
  0.00    0.000099          33         3           madvise
  0.00    0.000076           2        28        22 faccessat
  0.00    0.000057          57         1           prlimit64
  0.00    0.000053          53         1           ioctl
  0.00    0.000042          21         2           sigaltstack
  0.00    0.000039          39         1           pipe2
  0.00    0.000038          38         1           sched_getaffinity
  0.00    0.000032          32         1           getuid
  0.00    0.000031          15         2           getrandom
  0.00    0.000029          29         1           epoll_pwait
  0.00    0.000026          26         1           gettid
  0.00    0.000026          26         1           epoll_create1
  0.00    0.000021          21         1           write
  0.00    0.000009           9         1           sched_yield
  0.00    0.000000           0         1           set_tid_address
  0.00    0.000000           0         1           sched_getscheduler
  0.00    0.000000           0         1           getpid
  0.00    0.000000           0         1           execve
------ ----------- ----------- --------- --------- -------------------
100.00    2.728270          16    166433        36 total
```

**Comment by iawia002** [comment]
> The early version was installed via Homebrew and updated to v0.24.1 today in the terminal with "brew upgrade lux".

Got it, the [install script](https://github.com/Homebrew/homebrew-core/blob/master/Formula/l/lux.rb#L22) in homebrew needs an update
